# Generated by Django 3.1.7 on 2021-03-22 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection', models.CharField(blank=True, max_length=255, null=True)),
                ('userA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to='users.userprofile')),
                ('userB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='users.userprofile')),
            ],
        ),
    ]
